### ISSUE TITLE
Lack of "X-Presto-"* headers for `httr::POST` or `httr::DELETE` requests

### ISSUE THREAD

**Issue by chezou** [prestodb/RPresto#103]
Since `dbFetch` and `dbClearResult` functions don't set "X-Presto-"* headers with `httr::POST` and `httr::DELETE` functions, RPresto doesn't work for our Presto cluster.

```R
> while (!dbHasCompleted(res)) {
+ chunk <- dbFetch(res)
+ print(chunk)
+ }
```

```R
GET call failed with error: "Unauthorized (HTTP 401).", retrying [1/3]

GET call failed with error: "Unauthorized (HTTP 401).", retrying [2/3]

GET call failed with error: "Unauthorized (HTTP 401).", retrying [3/3]
```

Work around got from #83 work fine, but I think RPresto should handle "X-Presto-"* headers for `dbFetch` and `dbClearResult` functions.

Here is the work around.

```R
> httr::set_config(
+ httr::add_headers("X-Presto-User"=Sys.getenv("USER"))
+ )
> res <- dbSendQuery(con, 'SELECT 1')
> while (!dbHasCompleted(res)) {
+ chunk <- dbFetch(res)
+ print(chunk)
+ }
data frame with 0 columns and 0 rows
  _col0
1     1
```

**Comment by onurfiliz** [comment]
Hmm, it's interesting, this does not fail in our clusters. What are the presto and RPresto versions you are on?

In any case, this should be a relatively safe and easy fix, we'll look into it.

**Comment by chezou** [comment]
Thanks. I use RPresto v1.3.2 from CRAN and our Presto version is 0.205.
Our company is providing managed Presto service and we need to send our API key on a header for authentication.

JFYI, I made a patch for this issue but I can't fix httr mocking for test. https://github.com/chezou/RPresto/commit/1fe98d5d4f8750c6fc83d097ab7fc74314260b49

**Comment by xerial** [comment]
@onurfiliz FYI. presto-jdbc is already setting X-Presto-User header for every HTTP request:
https://github.com/prestodb/presto/blob/eeaafc849456c640bfe35ff47880e12ac697a574/presto-client/src/main/java/com/facebook/presto/client/StatementClientV1.java#L314

In our specific case, we are using `X-Presto-User: (token)` for authenticating query requests.
