### ISSUE TITLE
Connecting to Presto using Username and Password 

### ISSUE THREAD

**Issue by sjahanbin** [prestodb/RPresto#111]
Hello,

I have been trying to connect to Presto using username and password; however as dbConnect() doesn't have password argument-see below code. I will keep getting below error.

--Code:
library(RPresto)
library(dbConnect)

DBI::dbConnect(RPresto::Presto(), catalog = 'hive', schema = 'default', user = 'XXXXX', host = '10.xx.xx.xxx', port = 8989)

DBI::dbSendQuery(conn, 'SELECT 1')

--Error:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to 10.xx.xx.xxx port 8989: Connection refused

I have tried all the suggestions on issue #83 ;however the same issue still exist, and I keep getting the above error. Here is some of the code I used to run prior to the above codes: 

--Scenario 1:
library(glue)

username='xxxxxxx'
pw='xxxxxxx'

httr::set_config(
  httr::config(
    httpauth=1,
    userpwd=glue('{username}:{pw}'),
    ssl_verifypeer=0,
    cainfo='...',
    capath='...'
  )
)

--Scenario 2:
library(glue)

username='xxxxxxx'
pw='xxxxxxx'

httr::set_config(
  httr::config(
    httpauth=1,
    userpwd=glue('{username}:{pw}'),
    ssl_verifypeer=0
  )
)

--Scenario 3:
library(httr)

authenticate("XXXXX", "XXXXXX")

--Scenario 4:
auth_wrapper <- function(f) {
  return(
    function(...) {
      httr::with_config(
        httr::config(userpwd="XXXXX:XXXXXX"),
        f(...)
      )
    }
  )
}

dbSendQuery <- auth_wrapper(DBI::dbSendQuery)

**Comment by onurfiliz** [comment]
Have you resolved this? It depends somewhat on your authorization setup, so more information on that would be helpful. You should also prefix the host ip with the suitable protocol, like `http://` or `https://`. 

Also make sure you can access your server outside of R through an alternative http client like curl. You'd be making a call to `/v1/statement`, see https://github.com/prestodb/presto/wiki/HTTP-Protocol. Once you have a working curl command for that initial address, we can help you move forward.

**Comment by onurfiliz** [comment]
I'll close this. Please feel free to reopen if you are still having issues.
