### ISSUE TITLE
Error ocurred under R 3.6.1 environment

### ISSUE THREAD

**Issue by AxlZ** [prestodb/RPresto#113]
I was using R 3.6.1 to connect presto by RPresto package. I followed the Official document,but after establish the dbConnect() object and do the dbGetQuery(), this error occurred.I check many things like environment,arguments,network,but still can not find the reason.
--
Code:

library(RPresto)

library(DBI)

conn <- dbConnect(Presto(), catalog = 'hive', schema = 'aaa',
             user = 'bbb', host = '11.111.11.111', port = 8080)

dbGetQuery(conn, 'SELECT * FROM test LIMIT 1')

Error:

Error in if (is_http) { : argument is of length zero

And the Traceback:

6: request_perform(req, hu$handle$handle)

5: httr::POST(url, body = enc2utf8(statement), config = headers)

4: dbSendQuery(conn, statement, ...)

3: dbSendQuery(conn, statement, ...)

2: dbGetQuery(conn, "select * from test limit 1")

1: dbGetQuery(conn, "select * from test limit 1")

**Comment by onurfiliz** [comment]
Have you resolved this? If not, can you also provide the output of `sessionInfo()`, making sure that at the very least it contains the `httr` and `DBI` versions?

**Comment by onurfiliz** [comment]
Actually I've just noticed you are not specifying the protocol in your host specification. Can you also try after prefixing the ip with `http://` (or `https://` if that is your setup)?

**Comment by AxlZ** [comment]
> Actually I've just noticed you are not specifying the protocol in your host specification. Can you also try after prefixing the ip with `http://` (or `https://` if that is your setup)?

Thank you very much for your recommendation, after add the prefixing http, it is resolved
