### ISSUE TITLE
RPresto with Hive through SSL (https://)

### ISSUE THREAD

**Issue by itzkunalsatpute** [prestodb/RPresto#115]
Hi Team,

My task is to connect R with Presto which can fetch hive queried, I was successful to fetch hive tables by using RPresto package via http request. below is my code for simple http call

library(dplyr)
library(RPresto)
db <- src_presto(
  host='http://www.abc.com',
  port=XXXX,
  user=Sys.getenv('USER'),
  schema='dafault',
  catalog='hive'
)

db_results <- tbl(db,"test")

But I want a user to get prompt while connecting r via presto. Example after running above query user should get prompt to enter his LDAP credentials. Once it get succesfully then only user be able to fetch tables

My Try: Changes the above code with sufficing s

library(dplyr)
library(RPresto)
db <- src_presto(
  host='https://www.abc.com',
  port=(secure port number),
  user=Sys.getenv('USER'),
  schema='dafault',
  catalog='hive'
)

But I am getting below error after running above query

> db
Error in curl::curl_fetch_memory(url, handle = handle) :
  Peer's Certificate has expired.

Can anyone can help me on this?

**Comment by onurfiliz** [comment]
This is related to your SSL certificate setup and most likely not RPresto related. We leverage httr for http access which in turn relies on curl. I'd investigate at that level. Take a look at https://github.com/prestodb/RPresto/issues/83#issuecomment-385575706 for how you can provide additional configuration options.
Please feel free to reopen if you think this is related to RPresto itself.
