### ISSUE TITLE
Question around Licensing

### ISSUE THREAD

**Issue by DyfanJones** [prestodb/RPresto#117]
Hi all,

I am developing a package that creates a connection between R and AWS Athena [`RAthena`](https://github.com/DyfanJones/RAthena). I have receive a pull request correcting the dplyr SQL translations https://github.com/DyfanJones/RAthena/pull/31 . The pull request uses the RPresto interpretation. 

As the source code is coming from RPresto I am unsure if the license allows me to incorporate any of your source code.

Can anyone please advise how I can proceed (in term of licensing) if I want to use some of your source code in my package.

**Comment by DyfanJones** [comment]
I have changed the pull request so that it uses internal RAthena helper functions. The code now follows the dbplyr the guide: https://dbplyr.tidyverse.org/articles/new-backend.html with using  https://github.com/tidyverse/dbplyr/blob/master/R/backend-postgres.R as a guide. If there any issues please let me know.

**Comment by onurfiliz** [comment]
@DyfanJones our package is BSD-licensed and as such allows anything that license allows. I am not super well versed as to what's allowed, so you may need to do some research to see if it's OK.
Apologies that I cannot be of more help.
I'll close the the issue for now but feel free to reopen if there's more information needed.
