### ISSUE TITLE
check.status.code could be replaced by httr::stop_for_status()

### ISSUE THREAD

**Issue by hadley** [prestodb/RPresto#12]
(but you don't actually seem to use the function anywhere)

**Comment by cosinequanon** [comment]
Actually this function is used in 3 places, namely R/dbFetch.R, R/dbListFields.R, and R/dbSendQuery.R

**Comment by onurfiliz** [comment]
check.status.code is slightly different from httr::stop_for_status. The latter uses the http status code text as the error message, whereas the former uses the response body which in presto's case often contains more information about the error. 
That said, we should check if the body is empty and and fall back to the http status code text if necessary.

**Comment by hadley** [comment]
Ah ok - that's a good strategy.
