### ISSUE TITLE
Kerberos auth for the presto

### ISSUE THREAD

**Issue by nikhilbejugama** [prestodb/RPresto#121]
We get below error when trying to connect to the kerberos authenticated presto, 

```
> library('RPresto')
conn <- dbConnect(Presto(), catalog = '****', schema = '****', host = 'https://<hostname>', port = ***, user = 'username', AuthMech = "1");

> dbSendQuery(conn, 'show tables')
Error in check.status.code(post.response) :
  Received error response (HTTP 401): <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 Unauthorized</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    Unauthorized</pre></p>
</body>
</html>
```

I believe we need ome param which is similar to KerberosRemoteServiceName=“HTTP” or --krb5-remote-service-name HTTP to authenticate properly, but I was not able to figure it out.

Can someone please help me out with proper connection string to kerberos authenticated presto?

Please let me know if you need any additional details.

**Comment by leepface** [comment]
Given how long it's been, I'm going to close this. Feel free to comment if it's still relevant.
