### ISSUE TITLE
Connect Datalake from R on Kubernetes

### ISSUE THREAD

**Issue by sabarikannan-ai** [prestodb/RPresto#122]
library('RPresto')
library('DBI')

con <- dbConnect(
  RPresto::Presto(),
  host='',
  port=10500,
  user='',
  schema='', // it is a database ??
  catalog='hive', // hope it is hive
  source='' // what exactly it is ??
)

can you please explain each parameter. As per our understanding host, port,user would be fine.
What is schema , catalog and source .

We use keytab to connect datalake from k8 it is working fine in Python using Presto.

do we need rjava and httr to connect hive using RPresto.

**Comment by onurfiliz** [comment]
> can you please explain each parameter. As per our understanding host, port,user would be fine.
What is schema , catalog and source .

The `schema` and `catalog` are dependent on your particular Presto set up. Please see https://prestodb.io/docs/current/overview/concepts.html for what they stand for. `source` gets passed directly to Presto in the "X-Presto-Source" header. It identifies what library/package you are using to query the server. Allowed values _might_ again depend on your setup, but you most likely will be OK with just providing something like 'RPresto'.

> do we need rjava and httr to connect hive using RPresto.

Yes for 'httr', no for 'rJava'. Here's the full list: https://github.com/prestodb/RPresto/blob/master/DESCRIPTION#L17-L25.
