### ISSUE TITLE
Custom escape methods for date-times

### ISSUE THREAD

**Issue by hadley** [prestodb/RPresto#123]
I wasn't thinking when I merged https://github.com/tidyverse/dbplyr/pull/391 into dbplyr; the methods really should live in the individual backends. I'm going to remove these methods for the next dplyr release so can you please include in your package:

```R
#' @export
sql_escape_date.PrestoConnection <- function(con, x) {
  paste0('date ', dbQuoteString(con, as.character(x)))
}

#' @export
sql_escape_datetime.PrestoConnection <- function(con, x) {
  x <- strftime(x, "%Y-%m-%d %H:%M:%OS %Z")
  paste0('timestamp ', dbQuoteString(con, x))
}
```

The code comes from [OssiLehtinen](https://github.com/OssiLehtinen) so please credit him

**Comment by onurfiliz** [comment]
Thanks @hadley for the heads up and @OssiLehtinen providing the implementations. `date` looks good, but I have concerns about `datetime` and time zone handling. Going over `strftime` man page, I'm seeing:

> %Z Time zone abbreviation as a character string
          (empty if not available).  This may not be reliable when a
          time zone has changed abbreviations over the years.

Especially the potential for being empty is concerning. Do you have an intuition as to when/which platforms that could happen in? 

Presto implements the concept of the session timezone. If the timestamp is missing a timezone specification, then it is interpreted to be in the session timezone. If that's different from the time zone for the client's machine, then we'd have inconsistencies/bugs.

I'm leaning towards working with the unixtime directly (`paste0('FROM_UNIXTIME(', as.numeric(x), ')')`) to reduce the reliance on timezone particulars. What do you think?

**Comment by hadley** [comment]
Ah, good point. Time zone abbreviations are fundamentally ambiguous and best avoided.

I think your approach is correct, but I always find these things hard to reason about. Another option is to force the UTC timezone in `strftime()`:

``` r
timestamp <- function(x) {
  strftime(x, "%Y-%m-%d %H:%M:%OSZ", tz = "UTC")
}

x <- Sys.time()
x
#> [1] "2020-10-01 16:02:22 CDT"
timestamp(x)
#> [1] "2020-10-01 21:02:22Z"
```

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
