### ISSUE TITLE
Package version in DESCRIPTION lags behind CRAN Package version

### ISSUE THREAD

**Issue by alex-gable** [prestodb/RPresto#129]
[Cran](https://cran.r-project.org/web/packages/RPresto/index.html) lists the package at `1.3.6` whereas the DESCRIPTION file lists as `1.3.5`.

Nothing major, was just trying to reconcile some other package issues and track down updates.

**Comment by leepface** [comment]
Sorry about that. The version change just reflected me taking over as maintainer. Should be aligned now.
