### ISSUE TITLE
How does auth work?

### ISSUE THREAD

**Issue by hadley** [prestodb/RPresto#14]
After skimming through the code, I have no idea.

**Comment by electrum** [comment]
Currently, Presto does not have authentication or authorization. There are user and source parameters for queries, but those are advisory only (for the admin to see who/what is running queries).

**Comment by hadley** [comment]
So auth effectively happens at the network level?

**Comment by electrum** [comment]
Correct. Though we will be adding authentication and basic authorization in the near future.

**Comment by onurfiliz** [comment]
@hadley I'm hoping @electrum's answer clarifies the current situation so I will close this issue. Please feel free to reopen otherwise.

**Comment by dain** [comment]
In Presto we're working on adding Kerberos SSO via HTTP SPNEGO.  Once that lands, we should be able to add that to clients like this.

**Comment by bearloga** [comment]
Is it possible to get Kerberos auth support similar to `prestodb.auth.KerberosAuthentication` in [presto-python-client](https://github.com/prestodb/presto-python-client/blob/master/prestodb/auth.py)?
