### ISSUE TITLE
adding Kerberos support

### ISSUE THREAD

**Issue by copernican** [prestodb/RPresto#202]
Presto supports Kerberos authentication. RPresto support for Kerberos has been discussed previously (#83, #121), but it doesn't seem like it was ever implemented. An implementation could be something like

1. add an argument to `dbConnect()` like `use.kerberos.headers`
2. modify the various `db*` functions, like `dbSendQuery()`, so that httr functions like `authenticate()` get an argument `type = "gssnegotiate"`

Would opening a PR be helpful?

**Comment by copernican** [comment]
Thanks for the suggestion. Let me see if I can make it work using `parameters`. I'll update this issue with my findings.

**Comment by jarodmeng** [comment]
> Hello. We recently updated our internal `RPresto` fork with `1.4.0` and here are our new approach for Kerberos integration:
> 
> 1. When connecting to Kerberos-authenticated presto server, add the following arguments in `httr::POST` and `httr::DELETE` calls from `PrestoQuery` and `dbClearResult`.
>    a.  `request.config`
>    b. `httr::authenticate(user = "", password = "", type = "gssnegotiate")`
> 2. RPresto client/user will need to set the below arguments to connect to secure Presto:
>    a. `extra.credentials` with `use.kerberos.headers=TRUE`
>    b. `request.config` with `httr::config(ssl_verifypeer=FALSE,ssl_verifyhost=FALSE)`
> 
> Test cases were also updated to cover testing with Kerberos-authenticated Presto connection. Let us know if you are Ok with this approach so we can open a PR for Kerberos integration in `RPresto`. Thank you!

Sounds good. Feel free to create a PR on this.

**Comment by suzzettedetorres** [comment]
Thanks @jarodmeng , kindly help check: https://github.com/prestodb/RPresto/pull/221.
cc: @copernican

**Comment by jarodmeng** [comment]
This is fixed by #224.

**Comment by suzzettedetorres** [comment]
Hello @jarodmeng . Is there a chance the [Kerberos integration](https://github.com/prestodb/RPresto/commit/6178e071174744d6cd4c38f763ef6607395deb25) commit will be included in the next release?

**Comment by jarodmeng** [comment]
> Hello @jarodmeng . Is there a chance the [Kerberos integration](https://github.com/prestodb/RPresto/commit/6178e071174744d6cd4c38f763ef6607395deb25) commit will be included in the next release?

Yes. It will be included in 1.4.2. Right now, it's in the development version 1.4.1.9000.

**Comment by suzzettedetorres** [comment]
Hello @jarodmeng . Follow-up on this one. When can we expect the next release `1.4.2`? Thank you.

**Comment by jarodmeng** [comment]
> Hello @jarodmeng . Follow-up on this one. When can we expect the next release `1.4.2`? Thank you.

 I plan to release it in the 2nd half of Jan.
