### ISSUE TITLE
Bug on RPresto v1.4.0 relate to tbl(aws_con, in_schema('sel_schema','sel_table'))

### ISSUE THREAD

**Issue by charlvit** [prestodb/RPresto#217]
Hi there, found bug on RPresto 1.4.0. When connect to aws and use tbl function with in_schema, there was an error as below. Previous v.1.3.7 is ok. Seem like new version 1.4.0 did not replace 'default' schema with new one defined in in_schema(). Could you reproduce and confirm the bug?
https://user-images.githubusercontent.com/50406769/200525965-986114f9-dc9c-49a5-8cbb-38fb10b33538.png

**Comment by jarodmeng** [comment]
Is this the same issue reported in #200 ? If yes, you can get the latest Github version, i.e. 1.4.0.9000 to see if it has been fixed for you.

**Comment by charlvit** [comment]
Hi jarodmeng, yes it is the same issue. My company only allow install from cran. I will use 1.3.7 till the new version publish on cran. Thanks for quick response. For the new version, I really like support for bigint & the progress status when query big data :-)

**Comment by jarodmeng** [comment]
I can roll out a 1.4.1 version to CRAN soon with the in_schema() fix, if that helps.

**Comment by charlvit** [comment]
Yes, please. 1.4.1 with in_schema() fix is really help me and others who faced the same issue. Thanks a lot.

**Comment by charlvit** [comment]
> I can roll out a 1.4.1 version to CRAN soon with the in_schema() fix, if that helps.

Yes, please. 1.4.1 with in_schema() fix is really help me and others who faced the same issue. Thanks a lot.

**Comment by jarodmeng** [comment]
> > I can roll out a 1.4.1 version to CRAN soon with the in_schema() fix, if that helps.
> 
> Yes, please. 1.4.1 with in_schema() fix is really help me and others who faced the same issue. Thanks a lot.

Okay. I will wait for the PR from #202 to come in. If I can get the PR worked out, I will release a 1.4.1 this week.

**Comment by charlvit** [comment]
> > > I can roll out a 1.4.1 version to CRAN soon with the in_schema() fix, if that helps.
> > 
> > 
> > Yes, please. 1.4.1 with in_schema() fix is really help me and others who faced the same issue. Thanks a lot.
> 
> Okay. I will wait for the PR from #202 to come in. If I can get the PR worked out, I will release a 1.4.1 this week.

Hi Jarodmeng, Thanks a lot.

**Comment by jarodmeng** [comment]
@charlvit I just released RPresto 1.4.1 to CRAN.

**Comment by charlvit** [comment]
> @charlvit I just released RPresto 1.4.1 to CRAN.

Hi Jarodmeng, Thanks a lot. I will update my production server tomorrow to 1.4,1 :-)
