### ISSUE TITLE
Add "client-tags" support

### ISSUE THREAD

**Issue by KimShen** [prestodb/RPresto#225]
RPresto supports "client-tags" like Java Client:
java -jar presto-cli-0.277-executable.jar  --server x.x.co:80 --catalog hive --source ai --client-tags passwd=1234556,adhoc,label=adhoc  --user xxx

**Comment by jarodmeng** [comment]
Does the tags basically go to the "X-Presto-Client-Tags" header?

**Comment by KimShen** [comment]
> Does the tags basically go to the "X-Presto-Client-Tags" header?

Yes~, and how to set "X-Presto-Client-Tags" header？Tks

**Comment by KimShen** [comment]
Thanks helpful and closed.
###################
conn_config = add_headers("X-Presto-Client-Tags" = "xxx")
conn = RPresto::dbConnect(Presto(),catalog = 'hive',source = "ai",schema = "default",user = 'us', host = '127.0.0.1',port = 8888,request.config = conn_config)
###################
