### ISSUE TITLE
Is R 3.1.1 really needed?

### ISSUE THREAD

**Issue by jeffwong** [prestodb/RPresto#23]
I have some servers that run R 3.1.0. Is R 3.1.1 really needed? It'd be nice if the R version requirement was around 3.0

**Comment by cosinequanon** [comment]
This is just what we were using when we developed it. It will probably work with 3.1.0, you should try it out.

**Comment by onurfiliz** [comment]
I don't think we are using anything R-3.1 specific. But unfortunately I cannot find a working combination of 'jsonlite', 'httr' and 'testthat' where they all support R-3.0 and provide the functions we are using in RPresto and/or the test suite. So in the absence of testing, we should keep it at 3.1.x. But 3.1.0 should be fine.

**Comment by jeffwong** [comment]
I've tested this through a fork on several machines and R 3.1.0 is fine. Can you downgrade the R requirement? I don't want to ask people to install_github from my fork

**Comment by cosinequanon** [comment]
All the tests pass on 3.1.0 so I am okay with this. Can you send us a PR?
