### ISSUE TITLE
Passing key values using `extra.credentials`

### ISSUE THREAD

**Issue by pawelpalgan** [prestodb/RPresto#239]
Hi there,

First of all thanks for your work on a very useful piece of software. I am not sure if it is a bug, but I was not able to find a way to pass more than one pair of key values using `extra.credentials`.

When using `trino-python-client` it can be done simply by `extra_credential=[('extra_login', 'my_extra_login'), ('extra_password', 'my_extra_password')]` as detailed here https://github.com/trinodb/trino-python-client#extra-credentials

Trino official JDBC driver also provides similar approach to pass a list of key value pairs https://trino.io/docs/current/client/jdbc.html#parameter-reference
 
I have tried a couple of different approaches but with no success. Could you please clarify if it can be done and if so, how exactly?

Thanks!

**Comment by jarodmeng** [comment]
Have you tried passing the multiple keys in a comma-separated string, e.g., `key=value[,key=value,...]`?

**Comment by pawelpalgan** [comment]
Actually I have tried several separators between the pairs, like comma, colon, semicolon. I have also tried to escape them, but to no avail. I am getting `invalid login/password` from remote database with needs this extra authorization. Since I have very limited debugging options, my guess is that those values are indeed passed but in some malformed state. 

When I drop `extra.credentials` from my connection everything works fine. I can work with all my trino databases, except for that one which needs separate credentials.

**Comment by jarodmeng** [comment]
Does passing the extra credentials via the python client work? RPresto simply pass the string you supply in the `extra.credentials` field to Trino without modification. I checked using a small example that the string is indeed passed via the `X-Trino-Extra-Credential` header.

Also, have you set `use.trino.headers` to `TRUE`?

**Comment by pawelpalgan** [comment]
I can confirm that both, setting `use.trino.headers` to `TRUE` and separating key value pairs with coma in `extra.credentials` make connection working as expected. Thank you for your help!
