### ISSUE TITLE
Some Tests Fail When Locale is Not UTF-8

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/RPresto#25]
Here is what I am seeing

```
> devtools::test()
Loading RPresto
Testing RPresto
check.status.code : ..
data types : ....................
dbClearResult : .....
dbConnect : .....
dbDataType : .......................
dbDisconnect : ..
dbExistsTable : ...
dbFetch : ........................1..
dbGetInfo : .............
dbGetQuery : .2.3
dbGetRowCount : .............
dbGetStatement : ........
dbHasCompleted : ..........
dbIsValid : ..................................
dbListFields : ..............
dbListTables : ....
dbSendQuery : ...................
dbUnloadDriver : .
dplyr : .....
.extract.data : .4..
fetch : .........
get.state : ...
integration : ..............
.json.tabular.to.data.frame : ...........................
PrestoCursor : ...................
response.to.content : 5
stop.with.error.message : .
wait : .

1. Failure (at utilities.R#28): dbFetch rbind works correctly ------------------
r not equal to e
Component "<odd_name>": 2 string mismatches

2. Failure (at test-dbGetQuery.R#19): dbGetQuery works with live database ------
dbGetQuery(conn, "SELECT t FROM (VALUES ('\303\247\304\237\304\261\303\266\305\237\303\274'), ('\303\207\304\236\304\260\303\226\305\236\303\234')) AS a (t)") not equal to data.frame(t = c("\303\247\304\237\304\261\303\266\305\237\303\274", "\303\207\304\236\304\260\303\226\305\236\303\234"), stringsAsFactors = FALSE)
Component "t": 2 string mismatches

3. Failure (at test-dbGetQuery.R#27): dbGetQuery works with mock ---------------
dbGetQuery(conn, "SELECT t FROM encoding_test") not equal to data.frame(t = c("\303\247\304\237\304\261\303\266\305\237\303\274", "\303\207\304\236\304\260\303\226\305\236\303\234"), stringsAsFactors = FALSE)
Component "t": 2 string mismatches

4. Failure (at utilities.R#28): extract.data works -----------------------------
r not equal to e
Component "<odd_name>": 2 string mismatches

5. Failure (at test-response.to.content.R#28): response.to.content works -------
response.to.content(response) not equal to list(extra = "content", stats = list(state = "dummy_state"), id = "dummy_url", columns = list(list(name = "l", type = "boolean", typeSignature = list(rawType = "boolean", typeArguments = list(), literalArguments = list())), list(name = "m", type = "bigint", typeSignature = list(rawType = "bigint", typeArguments = list(), literalArguments = list())), list(name = "n", type = "varchar", typeSignature = list(rawType = "varchar", typeArguments = list(), literalArguments = list()))), data = list(list(TRUE,
    "NA", "\303\266\304\237\304\261\305\237\303\274\303\247\303\226\304\236\304\260\305\236\303\234\303\207")))
Component "data": Component 1: Component 3: 1 string mismatch
```

This all goes away if you run `Sys.setlocale("LC_ALL", 'en_US.UTF-8')` first

**Comment by dain** [comment]
In main Presto we are about to switch running in a locale like USASCII that will break bad code that uses the system locale.  We also run all tests in the time zone "Asia/Katmandu" to assure that we are not assuming the process is running in UTC (or the FB favorite PST).

**Comment by onurfiliz** [comment]
@dain can we assume that as long as we set X-Presto-Language=en_US.UTF-8 the whole response will be utf-8 encoded? What happens with e.g. date representations if we use something other than en_US?

And if we set X-Presto-Time-Zone=UTC, what happens with "timestamp with time zone" and "timestamp" data types?

**Comment by onurfiliz** [comment]
Oh and for posterity, what is the expected encoding of the POST request body when the -Language header is set to something other than utf-8?

**Comment by dain** [comment]
Presto responses are in JSON which is UTF8 by spec, so Presto responses are always UTF-8.  The `X-Presto-Language` header controls the rendering of functions like parse and print of dates.  The support for locales is not fully implemented in Presto so, some functions may not respect the client locale.

The `X-Presto-Time-Zone` sets the default timezone for the session.  In SQL all timestamps are evaluated with respect to a timezone.  In the case of, `timestamp with time zone` the time zone is explicit in the data (each value can have a different time zone), and in the case of `timestamp` the time zone is the session time zone.  One thing to note is in both cases the `instant` at which the timestamp occurs is fixed, and the time zone is only used for parsing, rendering and performing calculations on `fields` (e.g. add one hour).
