### ISSUE TITLE
Error with dbFetch on Presto 0.77

### ISSUE THREAD

**Issue by ricardo-bion** [prestodb/RPresto#3]
`dbFetch()` throws an error because it expects three columns (`name`, `type`, and `typeSignature`), and `dbSendQuery()` returns only two (`name`, and `type`).

![screen shot 2015-04-18 at 2 15 09 pm](https://cloud.githubusercontent.com/assets/9888486/7221851/f72e0862-e6b1-11e4-99e2-4524f546af6a.png)

![screen shot 2015-04-18 at 2 16 40 pm](https://cloud.githubusercontent.com/assets/9888486/7221859/3046f7d0-e6b2-11e4-9f59-e41cb87d7b36.png)

https://github.com/prestodb/RPresto/blob/master/R/extract.data.R#L17

**Comment by cosinequanon** [comment]
@dain any idea if the response for the REST API has changed since version 0.77?

**Comment by electrum** [comment]
0.77 is very old. Please upgrade to 0.100.

**Comment by cberner** [comment]
Yes, it changed some time around version 0.77. That field was added as part of supporting array/map types

**Comment by cosinequanon** [comment]
Thanks guys, I'll close this out as something we won't fix.
