### ISSUE TITLE
Does RPresto allow command line arguments to be passed?

### ISSUE THREAD

**Issue by jeffwong** [prestodb/RPresto#32]

**Comment by cosinequanon** [comment]
No, but I think you should be able to pass in parameters to the request. What exactly are you trying to do?

**Comment by jeffwong** [comment]
At command line I can start presto with 
presto --session <some variable = >

**Comment by cosinequanon** [comment]
You should be able to add in arbitrary parameters when you connect like this:
```
con <- dbConnect(
  RPresto::Presto(),
  host='http://localhost',
  port=7777,
  user=Sys.getenv('USER'),
  schema='<schema>',
  catalog='<catalog>',
  parameters=list('optimize_hash_generation'='true')
)
```
I believe these extra parameters control the session, we obviously won't support all the CLI params (e.g. `--file`) but let us know if something you need is missing.
