### ISSUE TITLE
Add Support For dplyr

### ISSUE THREAD

**Issue by cosinequanon** [prestodb/RPresto#4]
We should add integration for dplyr, @hadley has stated that dplyr integration with any new backends do not belong dplyr. That said, I am not entirely sure that they belong in this repository either because the core point of RPresto is to provide DBI support for Presto. I'd love to hear other people's opinions on whether or not we would consider adding dplyr support here.

I have working code for the dplyr integration but will not be sending a PR until we have consensus.

**Comment by ricardo-bion** [comment]
I vote for RPresto providing both DBI support for Presto and dplyr integration. That might be easier than maintaining separate DBIPresto and dplyrPresto packages.

**Comment by hadley** [comment]
I think it's easier to have one package that does both - the extra dplyr code is fairly minimal, and most revolves around specifying the SQL dialect that presto uses
