### ISSUE TITLE
Support for integer data type in Presto

### ISSUE THREAD

**Issue by jmrohnson** [prestodb/RPresto#56]
Following the README, I tried running: 

```
res <- dbSendQuery(con, 'SELECT 1')
# dbFetch without arguments only returns the current chunk, so we need to
# loop until the query completes.
while (!dbHasCompleted(res)) {
    chunk <- dbFetch(res)
    print(chunk)
}
```
I get the error:   **Error in .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) : 
  Unsupported column type: NA** 

However, if I run res <- dbSendQuery(con, 'SELECT CAST(1 as BIGINT)'), I get the expected output.  

I understand that integer is not a supported data type for Presto, https://prestodb.io/docs/current/language/types.html, but they seem to exist anyways.   From my limited knowledge of things, I think all that needs to be done is to add a row to the Presto -> R conversion matrix that casts integer to integer, but not 100% sure.  I'm running on the latest version of RPresto, and on Presto version  0.147.

**Comment by cosinequanon** [comment]
I think the newest version of Presto does support INT as a type, I'll try and repro internally. If you can put up a PR that passes the tests we would be happy to review.
