### ISSUE TITLE
Unable to read the result from src_presto()

### ISSUE THREAD

**Issue by MichaelAlo** [prestodb/RPresto#78]
Hi guys, 

I have an issue with RPresto :(
It seems I cannot read the result from the query I submitted because of a problem between a html file and JSON.
Can you guys please help?

Here is my code:
drv = RPresto::Presto()
src = src_presto(catalog = "xxx", schema = "xxx", user = "xxx", host = "xxx", port = xxx, session.timezone = "UTC")
tbl1 = tbl(src, from = "uservent")

And when I run this, I have the following

> tbl1 = tbl(src, from = "uservent")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^

Cheers, 

Michael

**Comment by onurfiliz** [comment]
Which version are you using? This should be fixed with <https://github.com/prestodb/RPresto/commit/f9afe68>. Could you try the github version via `devtools::install_github`?

**Comment by MichaelAlo** [comment]
Hi, 
Thanks very much for your reply.
It was RPresto 1.2.1.
But when I try to install from github with the following code:

library(devtools)
devtools::install_github("hoxo-m/githubinstall")
library(githubinstall)
gh_suggest("RPresto")
gh_install_packages("RPresto")
Y
Y





I have an error:





C:/Users/micha/OneDrive/Documents/R/win-library/3.3/Rcpp/include/Rcpp/vector/Vector.h:73:5: note: Rcpp::Vector<RTYPE, StoragePolicy>::Vector(SEXP) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage; SEXP = SEXPREC*]
     Vector( SEXP x ) {
     ^
make: *** [check_names.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-33~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RPresto.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o check_names.o transpose.o"' had status 2
ERROR: compilation failed for package 'RPresto'
* removing 'C:/Users/micha/OneDrive/Documents/R/win-library/3.3/RPresto'
Installation failed: Command failed (1)


Do you have an idea of what it could be?

Cheers,

**Comment by MichaelAlo** [comment]
Hi Guys :)

Is there anyone to guide me on tackling this issue I have.
Is it related to a package I have or have not installed?

Thanks much for your help. :)

Michael

**Comment by onurfiliz** [comment]
Hmm, you seem to have a windows environment which I currently do not have immediate access to. Is this all you see in terms of error messages? @saurfang, any chance you tested the Rcpp PR (#58) on a windows machine, or currently have access to one and can try reproducing this?

**Comment by MichaelAlo** [comment]
Hi, 

Thanks for your reply.
Here is the command and the full error result produced.
Thanks very much for your help. :)

> gh_install_packages("RPresto")
Suggestion:
 - prestodb/RPresto  DBI-based adapter for Presto for the statistical programming language R.
Do you want to install the package (Y/n)?  Y
Installing "RPresto" package from GitHub, but already installed from CRAN.
This package is already installed. Are you sure you want to overwrite it (Y/n)?  Y
Downloading GitHub repo prestodb/RPresto@master
from URL https://api.github.com/repos/prestodb/RPresto/zipball/master
Installing RPresto
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/micha/AppData/Local/Temp/RtmpeUTeFy/devtools192c4efd4e77/prestodb-RPresto-f4fd604"  \
  --library="C:/Users/micha/OneDrive/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'RPresto' ...
** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c check_names.cpp -o check_names.o
check_names.cpp: In function 'SEXPREC* check_names(Rcpp::List, int)':
check_names.cpp:15:34: warning: passing NULL to non-pointer argument 1 of 'Rcpp::Vector<RTYPE, StoragePolicy>::Vector(const int&) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage]' [-Wconversion-null]
   CharacterVector column_names = NULL;
                                  ^
C:/RBuildTools/3.4/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c transpose.cpp -o transpose.o
C:/RBuildTools/3.4/mingw_32/bin/g++ -shared -s -static-libgcc -o RPresto.dll tmp.def RcppExports.o check_names.o transpose.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/i386 -lR
installing to C:/Users/micha/OneDrive/Documents/R/win-library/3.4/RPresto/libs/i386

*** arch - x64
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c check_names.cpp -o check_names.o
In file included from C:/RBuildTools/3.4/mingw_64/lib/gcc/x86_64-w64-mingw32/4.9.3/include/stddef.h:1:0,
                 from C:/RBuildTools/3.4/mingw_64/x86_64-w64-mingw32/include/inttypes.h:14,
                 from C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/hash/hash.h:25,
                 from C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/sugar/sugar.h:28,
                 from C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp.h:72,
                 from check_names.cpp:1:
check_names.cpp: In function 'SEXPREC* check_names(Rcpp::List, int)':
check_names.cpp:15:34: error: conversion from 'long long int' to 'Rcpp::CharacterVector {aka Rcpp::Vector<16>}' is ambiguous
   CharacterVector column_names = NULL;
                                  ^
check_names.cpp:15:34: note: candidates are:
In file included from C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/Vector.h:52:0,
                 from C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp.h:40,
                 from check_names.cpp:1:
C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/vector/Vector.h:128:5: note: Rcpp::Vector<RTYPE, StoragePolicy>::Vector(const int&) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage]
     Vector( const int& size ) {
     ^
C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/vector/Vector.h:107:5: note: Rcpp::Vector<RTYPE, StoragePolicy>::Vector(const char*) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage]
     Vector( const char* st ) {
     ^
C:/Users/micha/OneDrive/Documents/R/win-library/3.4/Rcpp/include/Rcpp/vector/Vector.h:73:5: note: Rcpp::Vector<RTYPE, StoragePolicy>::Vector(SEXP) [with int RTYPE = 16; StoragePolicy = Rcpp::PreserveStorage; SEXP = SEXPREC*]
     Vector( SEXP x ) {
     ^
make: *** [check_names.o] Error 1
Warning: running command 'make -f "C:/PROGRA~1/R/R-34~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.0/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="RPresto.dll" WIN=64 TCLBIN=64 OBJECTS="RcppExports.o check_names.o transpose.o"' had status 2
ERROR: compilation failed for package 'RPresto'
* removing 'C:/Users/micha/OneDrive/Documents/R/win-library/3.4/RPresto'
* restoring previous 'C:/Users/micha/OneDrive/Documents/R/win-library/3.4/RPresto'
Installation failed: Command failed (1)

**Comment by onurfiliz** [comment]
Michael can you try if this works now after @saurfang's fix?

**Comment by MichaelAlo** [comment]
Hi Guys,  

It is all working now. Thanks very much for this. Excellent work! :)
However, the src_presto() and tbl.src_presto() way to connect do not work for me.

Here is my code and the error messages I get:
> src = src_presto(catalog = "xxx", schema = "xxx", user = "xxx", host = "xxx", port = xxx, session.timezone = "UTC")

> tbl1 = tbl.src_presto(src, from = "xxx")

> src
Error in .description.from.info(info) : 
  could not find function ".description.from.info"

> tbl1
Source:   query [?? x 11]
Error in .description.from.info(info) : 
  could not find function ".description.from.info"

Do you have any idea of what is going wrong with this? 

Cheers, 

Mika

**Comment by onurfiliz** [comment]
Please provide as much information as possible regarding how your environment is set up. Specifically in this case, what 'library' calls you made is important. See: http://reprex.tidyverse.org/articles/reprex.html. Also:
- Make sure you are trying this in a clean environment.
- Prefer `tbl()` instead of `tbl.src_presto()`.

**Comment by MichaelAlo** [comment]
Hi, 
Thanks for this.
Here are the details:
``` r
library(devtools)     
library(githubinstall)
library(Rcpp)         
library(DBI)          
library(dbConnect)    
#> Loading required package: RMySQL
#> Loading required package: gWidgets
library(dplyr)        
#> 
#> Attaching package: 'dplyr'
#> The following object is masked from 'package:gWidgets':
#> 
#>     id
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(jsonlite)     
library(rjson)        
#> 
#> Attaching package: 'rjson'
#> The following objects are masked from 'package:jsonlite':
#> 
#>     fromJSON, toJSON
library(RJSONIO)      
#> 
#> Attaching package: 'RJSONIO'
#> The following objects are masked from 'package:rjson':
#> 
#>     fromJSON, toJSON
#> The following objects are masked from 'package:jsonlite':
#> 
#>     fromJSON, toJSON
library(RPresto)      
```
``` r
src = src_presto(catalog = "x", schema = "x", user = "x", host = "x", port = x, session.timezone = "x")
#> Error in src_presto(catalog = "report", schema = "live_report", user = "root", : could not find function "src_presto"
src                                                                                                                                                                         
#> Error in eval(expr, envir, enclos): object 'src' not found
tbl1 = tbl(src, from = "trader")                                                                                                                                            
#> Error in tbl(src, from = "trader"): could not find function "tbl"
```
But when I run it, this is what I have in the console (it is different):

> src = src_presto(catalog = "x", schema = "x", user = "root", host = "x", port = x, session.timezone = "x")
> src
Error in .description.from.info(info) : 
  could not find function ".description.from.info"
> #str(src)
> tbl1 = tbl(src, from = "trader")
> tbl1
Source:   query [?? x 11]
Error in .description.from.info(info) : 
  could not find function ".description.from.info"

Cheers

**Comment by onurfiliz** [comment]
It seems like your R environment is broken. It could happen if you have objects saved in the session, have things in your .Renviron, .Rprofile etc. In a command-line environment, you could prevent those from being loaded by launching R via `R --vanilla`, but not sure how to achieve the same in Windows. At the very least, this should work without problems:

    library('dplyr')
    library('RPresto')

    src <- src_presto(...)


As it stands, this does not look RPresto related.

**Comment by MichaelAlo** [comment]
Ok ok; I will look at this and get back to you.
Probably by resinstalling R.
Cheers! :)
