### ISSUE TITLE
License field for CRAN

### ISSUE THREAD

**Issue by hadley** [prestodb/RPresto#8]
For CRAN submission, I think you need `License: BSD_3_clause + file LICENSE`.

You may get some pushback from CRAN about including the complete source of the license in the package. I'm not sure what their current position on that is.

**Comment by ricardo-bion** [comment]
@onurfiliz Any updates on CRAN submission? Thanks!

**Comment by onurfiliz** [comment]
Hey @ricardo-bion , the last issue I want to resolve is #42 , after that we should be good to go. I'll move it up my queue if CRAN is a blocker for you.

**Comment by ricardo-bion** [comment]
Thanks! It's not a blocker, just easier to have it in production with dependency management. Awesome work!
