### ISSUE TITLE
Issue with dbSendQuery and dbGetQuery and upper case tables names in MySQL

### ISSUE THREAD

**Issue by MichaelAlo** [prestodb/RPresto#81]
Hi, 

I have this issue with RPresto: my tables are in MySQL and the names are in upper case.

When I try to execute a query with dbSendQuery+dbFetch or dbGetQuery, it seems that the path to the table has been put in lower case and therefore I receive the message that the table does not exist (case sensitive issue of MySQL I guess).

Is there any way to force the name of the table to be in upper case in the query or to make the connection not case sensitive?

Thanks for your help! :)

**Comment by cosinequanon** [comment]
I can definitely repro this but I think this might be an issue with Presto itself. When I issue a query from the presto command line I am seeing the same behavior so I'm not sure there is anything we can do from our end. I will reach out to the Presto team to see if they can fix it.

**Comment by cosinequanon** [comment]
Turns out this is a long standing issue with Presto and MySQL connector. Nothing we can do on our end, you can follow along here https://github.com/prestodb/presto/issues/2863

**Comment by MichaelAlo** [comment]
Yes indeed :)
I've sent a message to know what's the latest on it, hoping it's on its way to be fixed.
Apparently, I'm not the only one to have this issue.
Thanks for replying mate!
Cheers :)
