### ISSUE TITLE
Using "NULL AS col_name" fails.

### ISSUE THREAD

**Issue by talgalili** [prestodb/RPresto#84]
For example:

```r
sql_txt <- "
SELECT
    entity_id,
    NULL AS empty_column
FROM
 table_name
"
dbSendQuery(con, sql_txt)
```

Returns the error:
```
 in .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) : 
  Unsupported column type: NA
```

A possible solution is to use 
```
sql_txt <- gsub("NULL AS ", "cast(NULL AS BOOLEAN) AS ", sql_txt, ignore.case = TRUE)
```

But there may a better way to solve it.

**Comment by onurfiliz** [comment]
IMO we are doing the right thing by erroring out. The type of the `NULL` column is "unknown" as returned by presto:

    > SELECT TYPEOF(NULL);
     _col0
    ---------
    unknown

While we _could_ cast it to a reasonable default like logical, it feels magical and my current thinking is not to do that. If in the future presto starts returning 'unknown' for other things that cannot be represented in R as logical NA's, we'd have to start branching out by inspecting the actual data returned. I'd prefer the caller specify what data type they'd like explicitly.

That said, the error message is pretty opaque and could be improved for sure.

**Comment by onurfiliz** [comment]
@talgalili I'm closing the issue as a WONTFIX. Please feel free to reopen if you disagree.
