### ISSUE TITLE
Support for CHAR datatype

### ISSUE THREAD

**Issue by tp2750** [prestodb/RPresto#92]
I'm using RPresto to access a table which as a column of type "CHAR".

RPresto does not appear to understand that. The example below should illustrate the problem:

```
> dbGetQuery(con, "SELECT CAST('A' AS VARCHAR)")
  _col0
1     A

> dbGetQuery(con, "SELECT CAST('A' AS CHAR)")
Error in .json.tabular.to.data.frame(data.list, r.types, timezone = timezone) : 
  Unsupported column type: NA
```

Will this be easy to fix?

I'll be happy to try to fix it myself, but I need a bit of guidance.

**Comment by onurfiliz** [comment]
This has been fixed with #91. It's just not released to CRAN yet. You can install the development version with `devtools::install_github('prestodb/RPresto')`.

**Comment by tp2750** [comment]
Thanks a lot @onurfiliz , and sorry for not checking the github version first.

Thanks for a great project!

**Comment by onurfiliz** [comment]
No worries, it happens. Glad you find the project useful.
